---
version: "3.1"
services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    network_mode: ezarr_default
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=Switzerland
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS}
      - PUID=13009
      - PGID=13000
      - UMASK=002
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - ${HOME}/ezarr/config/sonarr-config:/config
      - /media:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - ${HOME}/ezarr/config/radarr-config:/config
      - /media:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - ${HOME}/ezarr/config/lidarr-config:/config
      - /media:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - ${HOME}/ezarr/config/readarr-config:/config
      - /media:/data
    ports:
      - "8787:8787"
    restart: unless-stopped

  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=13005
      - PGID=13000
      - UMASK=002
    volumes:
      - ${HOME}/ezarr/config/mylar-config:/config
      - /media:/data
    ports:
      - "8090:8090"
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=13009
      - AUDIOBOOKSHELF_GID=13000
    ports:
      - "13378:80"
    volumes:
      - /media/audiobooks:/audiobooks
      - /media/podcasts:/podcasts
      - ${HOME}/ezarr/config/audiobookshelf:/config
      - /media/audiobookshelf-metadata:/metadata

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - ${HOME}/ezarr/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${UID}
      - PGID=13000
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - ${HOME}/ezarr/config/jellyfin-config:/config
      - /media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ=America/Denver
      - WEBUI_PORT=8080
    volumes:
      - ${HOME}/ezarr/config/qbittorrent-config:/config
      - /media/torrents:/data/torrents
      - /media/downloads:/data/downloads
    restart: unless-stopped
